"""Load extracted claims from `data/claims/`.

Kept beside the resources rather than inside them, and the separation is the
point. A resource file is curated: hand-written, synced to Airtable, edited by
people. A claim file is *derived* — regenerated whenever extraction improves,
which would otherwise mean a machine pass rewriting files humans maintain.

One file per resource, mirroring `data/resources/`, so a change to one paper's
claims is one file in a diff and a reviewer can see what moved.

Verdicts do *not* live here, and that follows directly from the above: a file
regenerated by the next extraction pass is the worst possible home for a
judgement a person spent time on. They live in `evals/gold/claims.yml`, keyed
by claim id, and are applied at load time.

That file is separate from `evals/gold/tags.yml` on purpose. Tags record where
a *record* belongs, which is what classifier accuracy is measured against; a
claim verdict records whether a *sentence* was read correctly. Both come from
the same reviewer in the same sitting, and merging them would produce one
number that answers neither question.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

import yaml

from .models import (
    CLAIM_RELATIONS, Claim, ConfidenceClass, RelationType, Relationship,
    ReviewStatus,
)

REPO = Path(__file__).resolve().parent.parent.parent
DEFAULT_DIR = REPO / "data" / "claims"
DEFAULT_VERDICTS = REPO / "evals" / "gold" / "claims.yml"


class ClaimError(ValueError):
    """A claim file that will not load."""


def load_verdicts(path: str | Path = DEFAULT_VERDICTS) -> dict[str, dict]:
    """Human verdicts on claims, keyed by claim id.

    Absent is the normal state for most of them, exactly as with the tag gold
    set — an empty file here means nobody has checked yet, not that everything
    passed.
    """
    path = Path(path)
    if not path.exists():
        return {}
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return payload.get("claims") or {}


def slug_for(resource_id: str) -> str:
    """`resource:arxiv:2502.14143` -> `arxiv-2502.14143`, as for resources."""
    return resource_id.removeprefix("resource:").replace(":", "-")


def load_claims(directory: str | Path = DEFAULT_DIR,
                verdicts: dict[str, dict] | str | Path | None = DEFAULT_VERDICTS) -> list[Claim]:
    """Read every claim file, applying any verdicts, failing loudly on a bad one."""
    directory = Path(directory)
    if not directory.exists():
        return []

    if verdicts is None:
        verdicts = {}
    elif not isinstance(verdicts, dict):
        verdicts = load_verdicts(verdicts)

    claims: list[Claim] = []
    seen: dict[str, Path] = {}

    for path in sorted(directory.glob("*.yml")):
        try:
            payload = yaml.safe_load(path.read_text(encoding="utf-8"))
        except yaml.YAMLError as error:
            raise ClaimError(f"{path.name}: invalid YAML: {error}") from error
        if not isinstance(payload, dict) or not isinstance(payload.get("claims"), list):
            raise ClaimError(f"{path.name}: expected a `claims:` list")

        resource_id = payload.get("resource_id")
        if not resource_id:
            raise ClaimError(f"{path.name}: no resource_id — a claim with no source "
                             "resource cannot be traced back to anything")
        if slug_for(resource_id) != path.stem:
            raise ClaimError(f"{path.name}: resource_id {resource_id!r} implies "
                             f"{slug_for(resource_id)}.yml")

        for entry in payload["claims"]:
            try:
                claim = Claim(resource_id=resource_id, **entry)
            except (TypeError, ValueError) as error:
                raise ClaimError(f"{path.name}: {error}") from error

            # A verdict promotes the claim, and only a verdict does. This is
            # the one path from EXTRACTED to reviewed, so an extraction pass
            # cannot manufacture one however sure it sounds.
            if checked := verdicts.get(claim.id):
                claim.verdict = checked.get("verdict")
                claim.reviewed_by = checked.get("reviewer")
                claim.note = checked.get("note") or claim.note
                claim.review_status = ReviewStatus.REVIEWED
                try:
                    claim.__post_init__()
                except ValueError as error:
                    # Names the verdict file, not the claim file. The claim is
                    # fine; the judgement recorded against it is not, and
                    # sending someone to the wrong file wastes the trip.
                    raise ClaimError(f"in the verdict file: {error}") from error
            if claim.id in seen:
                raise ClaimError(f"{path.name}: duplicate claim id {claim.id!r}, "
                                 f"also in {seen[claim.id].name}")
            seen[claim.id] = path
            claims.append(claim)

    return claims


def save_claims(resource_id: str, claims: Iterable[Claim],
                directory: str | Path = DEFAULT_DIR) -> Path:
    """Write one resource's claims, preserving the order they were extracted in.

    Order is not alphabetical on purpose: a paper's claims read in sequence,
    and sorting them would scramble an argument into a list.
    """
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{slug_for(resource_id)}.yml"

    payload = {
        "resource_id": resource_id,
        "claims": [
            {k: v for k, v in claim.to_dict().items() if k != "resource_id"}
            for claim in claims
        ],
    }
    path.write_text(
        yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=88),
        encoding="utf-8",
    )
    return path


def claim_edges(claims: Iterable[Claim], *, topic_codes: set[str] | None = None,
                vocabulary=None) -> list:
    """The edges a claim contributes: back to its resource, out to its topics.

    Every one carries its confidence class and the text it was read from, so a
    consumer meeting one of these edges in isolation can still tell it apart
    from a citation and go back to the sentence behind it.

    A claim's topics come from its concepts when it has them, and from its own
    `topic_codes` otherwise. That is the derivation principle applied one level
    down: a statement's place in the taxonomy follows from what it argues
    about, rather than being asserted separately and then disagreeing with
    itself — which the two layers did, on `arxiv:2511.03434` claim 2, where
    the codes said 10.1 and 4.4 and the concept resolved to 5.3.

    The fallback matters during the changeover. Re-extraction drops
    `topic_codes`, and without it 62 claim-to-topic edges vanished from the
    graph in one commit with nothing failing except a test that happened to
    assert the edge kind still existed.
    """
    edges: list[Relationship] = []
    for claim in claims:
        edges.append(Relationship(
            source_id=claim.resource_id,
            target_id=claim.id,
            relation=RelationType.MAKES_CLAIM,
            confidence_class=claim.confidence_class,
            source_resource_id=claim.resource_id,
            source_location=claim.extracted_from,
            extraction_method=claim.extraction_method,
        ))
        derived: list[str] = []
        if vocabulary is not None and claim.concept_tags:
            for tag in claim.concept_tags:
                concept = vocabulary.get(tag)
                for code in (concept.topics if concept else ()):
                    if code not in derived:
                        derived.append(code)
        for code in (derived or claim.topic_codes):
            if topic_codes is not None and code not in topic_codes:
                continue
            edges.append(Relationship(
                source_id=claim.id,
                target_id=f"topic:{code}",
                relation=RelationType.ABOUT,
                # A claim's topic is an inference from its text, not something
                # read out of the source the way the claim itself was.
                confidence_class=ConfidenceClass.INFERRED,
                source_resource_id=claim.resource_id,
                extraction_method=claim.extraction_method,
            ))
    return edges


def coverage(claims: Iterable[Claim]) -> dict:
    """How much of the claim layer has been checked by a person."""
    claims = list(claims)
    reviewed = [c for c in claims if c.review_status is ReviewStatus.REVIEWED]
    return {
        "claims": len(claims),
        "resources": len({c.resource_id for c in claims}),
        "reviewed": len(reviewed),
        "accurate": len([c for c in reviewed if c.verdict == "accurate"]),
        "overstated": len([c for c in reviewed if c.verdict == "overstated"]),
        "not_in_source": len([c for c in reviewed if c.verdict == "not-in-source"]),
    }


DEFAULT_RELATIONS = Path(__file__).resolve().parent.parent.parent / "data" / "claim-relations.yml"


def load_claim_relations(path: str | Path = DEFAULT_RELATIONS,
                         claims: Iterable[Claim] | None = None) -> list[Relationship]:
    """Read the claim-to-claim relations, refusing any that dangle.

    Both endpoints must be claims we actually hold. A relation pointing at a
    claim id that no longer exists is not a small problem here: the editorial
    pass cuts claims, and a cut claim leaving a live edge behind would mean
    the graph asserts a disagreement between a statement and nothing.

    Every relation is inferred, so `because` is required. The reasoning is
    the provenance — without it, a reader meeting one of these edges has no
    way to tell a considered judgement from a model's guess, which is the
    distinction this repository exists to keep.
    """
    path = Path(path)
    if not path.exists():
        return []

    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    entries = payload.get("relations") or []
    known = {c.id for c in claims} if claims is not None else None

    relations: list[Relationship] = []
    for position, entry in enumerate(entries, start=1):
        where = f"{path.name} entry {position}"
        for required in ("source", "target", "relation", "because"):
            if not entry.get(required):
                raise ClaimError(f"{where}: missing `{required}`")

        try:
            relation = RelationType(entry["relation"])
        except ValueError as error:
            raise ClaimError(f"{where}: unknown relation {entry['relation']!r}") from error
        if relation not in CLAIM_RELATIONS:
            raise ClaimError(
                f"{where}: {relation.value} is not a claim-to-claim relation; "
                f"expected one of {sorted(r.value for r in CLAIM_RELATIONS)}")

        if entry["source"] == entry["target"]:
            raise ClaimError(f"{where}: a claim cannot relate to itself")
        if known is not None:
            for end in ("source", "target"):
                if entry[end] not in known:
                    raise ClaimError(
                        f"{where}: {end} {entry[end]!r} is not a claim we hold — "
                        "it was cut, renamed, or never extracted")

        relations.append(Relationship(
            source_id=entry["source"],
            target_id=entry["target"],
            relation=relation,
            confidence_class=ConfidenceClass(entry.get("confidence_class", "INFERRED")),
            source_location=entry["because"],
            extraction_method=(
                f"asserted by {entry.get('asserted_by', 'unattributed')}"
                f" on {entry.get('asserted_on', 'an unrecorded date')}"),
        ))
    return relations


def candidate_pairs(claims, relations=None, *, across_papers_only: bool = True):
    """Claim pairs worth reading, because they share a concept.

    The arithmetic that makes the statement layer tractable. Forty claims is
    780 pairs, which nobody will read; requiring a shared concept tag cuts
    that to 73, and requiring the two claims to come from different papers
    cuts it to 27. The tags do the filtering so a person only spends
    judgement where there is something to judge.

    Sharing a concept is emphatically not a relation — most candidates
    should come back as nothing. A high yield would mean the vocabulary is
    too loose rather than that the corpus is unusually connected.

    Same-paper pairs are excluded by default because their relations are
    mostly premise-to-conclusion, which is a different reading task and
    better done as its own pass. Pass `across_papers_only=False` for those.
    """
    import itertools

    settled = set()
    for relation in relations or []:
        settled.add((relation.source_id, relation.target_id))
        settled.add((relation.target_id, relation.source_id))

    pairs = []
    for left, right in itertools.combinations(sorted(claims, key=lambda c: c.id), 2):
        if across_papers_only and left.resource_id == right.resource_id:
            continue
        shared = sorted(set(left.concept_tags) & set(right.concept_tags))
        if not shared or (left.id, right.id) in settled:
            continue
        pairs.append((left, right, shared))
    # Densest concept first: a reviewer working one idea at a time is both
    # faster and more consistent than one jumping between subjects.
    return sorted(pairs, key=lambda p: (-len(p[2]), p[2][0], p[0].id, p[1].id))
